"""Solid waste and sewage generation engineering constants."""

from __future__ import annotations

# Solid waste — kg per capita per day
RESIDENTIAL_WASTE_KG_PER_CAPITA_DAY = 0.45
COMMERCIAL_WASTE_KG_PER_CAPITA_DAY = 0.25

RESIDENTIAL_WET_WASTE_FRACTION = 0.60
RESIDENTIAL_DRY_WASTE_FRACTION = 0.40
COMMERCIAL_WET_WASTE_FRACTION = 0.40
COMMERCIAL_DRY_WASTE_FRACTION = 0.60

RESIDENTIAL_E_WASTE_KG_PER_CAPITA_YEAR = 1.0
COMMERCIAL_E_WASTE_KG_PER_CAPITA_YEAR = 1.5

GARDEN_WASTE_POP_DIVISOR = 47.25  # Residential Population / 47.25 = Garden Waste (kgs/day)

STP_SLUDGE_KG_PER_KLD_DAY = 0.20  # 370 KLD → 74 Kgs/Day

OWC_AREA_LOW_FACTOR = 70 / 900.0
OWC_AREA_HIGH_FACTOR = 75 / 900.0

# Sewage generation — population based (L/capita/day before 90% factor)
RESIDENTIAL_SEWAGE_LPCD = 135
COMMERCIAL_SEWAGE_LPCD = 45
SEWAGE_GENERATION_PERCENT = 0.90

SEWAGE_STP_AREA_LOW_FACTOR = 140 / 370.0
SEWAGE_STP_AREA_HIGH_FACTOR = 160 / 370.0
